name: colortiles
channels:
    - default
    - conda-forge
dependencies:
    - xarray
    - rasterio
    - scipy
    - jupyter
    - matplotlib
    - dask
    - netcdf4
    - pandas
    - xlrd
    - colour-science